# generated by Neptune Namespaces v1.x.x
# file: Art/Versioning/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Versioning'
.addModules
  CombinedVersion: require './CombinedVersion'
  Version:         require './Version'        