# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Versioning/index.coffee

module.exports = require './namespace'
.addModules
  Combine:   require './Combine'  
  Normalize: require './Normalize'
  Parse:     require './Parse'    
  Version:   require './Version'  