# generated by Neptune Namespaces v3.x.x
# file: tests/Art/Versioning/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CombinedVersion: require './CombinedVersion'
  Version:         require './Version'        