# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Versioning/index.coffee

module.exports = require './namespace'
.addModules
  CombinedVersion: require './CombinedVersion'
  Version:         require './Version'        