# generated by Neptune Namespaces v1.x.x
# file: tests/Art/Versioning/namespace.coffee

Art = require '../namespace'
module.exports = Art.Versioning ||
Art.addNamespace 'Versioning', class Versioning extends Neptune.Base
  ;